---
network_interfaces:
    - name: default
      mode: static
      mode6: disabled
      resolvermode: static
      routers:
        - 192.168.42.3
      resolvers:
        - 192.168.42.3

sshd_banner: assets/sshd_banner
sshd_AuthorizedKeysCommand: /usr/local/sbin/ssh_pubkeys
sshd_AuthorizedKeysFile: false
sshd_AllowGroupAlways: Server Admins

rsyslog_remote: nitrogen.collegiumv.org

telegraf_influxdb_remote: oxygen.collegiumv.org
telegraf_influxdb_db: collegiumv
telegraf_influxdb_password: "{{ lookup('file', 'secret/influxdb_telegraf') }}"
