---
influxdb:
  users:
    - name: cvadmin
      password: "{{ lookup('file', 'secret/influxdb_cvadmin') }}"
      admin: true
    - name: telegraf
      password: "{{ lookup('file', 'secret/influxdb_telegraf') }}"
      admin: false
  databases:
    - collegiumv
  privs:
    - user: telegraf
      database: collegiumv
      priv: write
  auth:
    user: cvadmin
    pass: "{{ lookup('file', 'secret/influxdb_cvadmin') }}"

chronograf_username: cvadmin
chronograf_password: "{{ lookup('file', 'secret/chronograf_password') }}"
