---
- name: Install postgres
  xbps:
    pkg:
      - acl-progs
      - postgresql
      - postgresql-client
      - postgresql-libs-devel
      - python-psycopg2
    state: present

- name: Enable PostgreSQL
  runit:
    name: postgresql
    enabled: yes
    state: started

- name: Check if postgresql-libs is held
  command: xbps-query postgresql-libs
  check_mode: no
  changed_when: false
  register: psql_libs

- name: Hold postgresql-libs
  command: xbps-pkgdb -m hold postgresql-libs
  when: "'hold: yes' not in psql_libs.stdout"

- name: Wait for PostgreSQL to start
  wait_for:
    port: 5432

- include: upgrade.yml
  when: postgresql_upgrade
