---
- name: Copy jira iptables rules
  copy:
    src: jira.rules
    dest: /etc/iptables.d/jira.rule
    owner: root
    group: root
    mode: 0640
  register: jira_iptables

- name: Enable jira iptables rules
  command: /usr/local/sbin/iptables-reload
  when: jira_iptables.changed

- name: Install oracle-jre
  xbps:
    pkg: oracle-jre
    state: present

- name: Copy nginx config
  copy:
    src: jira.conf
    dest: /etc/nginx/sites-available/jira.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - nginx

- name: Enable nginx config
  file:
    src: ../sites-available/jira.conf
    dest: /etc/nginx/sites-enabled/jira.conf
    state: link
  notify:
    - nginx

- name: Create Jira Database
  postgresql_db:
    name: jira_db
  become_user: postgres

- name: Create Jira Database User
  postgresql_user:
    db: jira_db
    name: jira_dbuser
    password: "{{ jira_dbpassword }}"
    priv: ALL
  become_user: postgres

- name: Create jira user
  user:
    name: jira
    home: '{{ jira_home }}'
    state: present

- name: Make directory for jira
  file:
    dest: '{{ jira_root }}'
    owner: root
    group: jira
    mode: 0775
    state: directory

- name: Extract jira
  unarchive:
    src: https://www.atlassian.com/software/jira/downloads/binary/atlassian-jira-software-7.5.0.tar.gz
    dest: '{{ jira_root }}'
    extra_opts: ['--strip-components=1']
    remote_src: true
    owner: jira
    group: jira
    creates: '{{ jira_root }}/NOTICE'

- name: Configure jira home
  template:
    src: jira-application.properties.j2
    dest: '{{ jira_root }}/atlassian-jira/WEB-INF/classes/jira-application.properties'
    owner: jira
    group: jira
    mode: 0644

- name: Create jira service directory
  file:
    dest: /etc/sv/jira
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Copy jira runit file
  template:
    src: jira.run.j2
    dest: /etc/sv/jira/run
    owner: root
    group: root
    mode: 0755

- name: Enable jira on boot
  runit:
    name: jira
    enabled: true
