---
- name: Install kerberos rules
  copy:
    src: kdc.rules
    dest: /etc/iptables.d/
    owner: root
    group: root
    mode: 0640
  notify:
    - iptables

- name: Install the kerberos packages
  xbps:
    pkg: mit-krb5
    state: present

- name: Ensure the kdc configuration directory exists
  file:
    path: /var/krb5kdc
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create the kdc configuration
  template:
    src: kdc.conf
    dest: /var/krb5kdc/kdc.conf
    owner: root
    group: root
    mode: 0644
  notify: krb5kdc

- name: Copy the kdc acl
  copy:
    src: kadm5.acl
    dest: /var/krb5kdc/kadm5.acl
    owner: root
    group: root
    mode: 0644
  notify: krb5kdc

- name: Configure KDC<->LDAP (1/3)
  template:
    src: kdc_stashpass.sh
    dest: /tmp/kdc_stashpass.sh
    owner: root
    group: root
    mode: 0700
  when: init

- name: Configure KDC<->LDAP (2/3)
  command: /tmp/kdc_stashpass.sh
  when: init

- name: Configure KDC<->LDAP (3/3)
  file:
    path: /tmp/kdc_stashpass.sh
    state: absent

- name: Bootstrap the KDC (1/3)
  template:
    src: kdc_bootstrap.sh
    dest: /tmp/kdc_bootstrap.sh
    owner: root
    group: root
    mode: 0700
  when: init and (inventory_hostname == groups['dc'][0])

- name: Bootstrap the KDC (2/3)
  shell: /tmp/kdc_bootstrap.sh
  when: init and (inventory_hostname == groups['dc'][0])

- name: Bootstrap the KDC (3/3)
  file:
    path: /tmp/kdc_bootstrap.sh
    state: absent

- name: Propogate the stash file (1/3)
  template:
    src: kdc_genstash.sh
    dest: /tmp/kdc_genstash.sh
    owner: root
    group: root
    mode: 0700
  when: init

- name: Propogate the stash file (2/3)
  shell: /tmp/kdc_genstash.sh
  when: init

- name: Propogate the stash file (3/3)
  file:
    path: /tmp/kdc_genstash.sh
    state: absent
  when: init

- name: Enable krb5 services
  file:
    src: "/etc/sv/{{ item }}"
    dest: "/var/service/{{ item }}"
    state: link
    owner: root
    group: root
  with_items:
    - krb5kdc
    - kadmind

- name: Wait for kdc to become available
  wait_for:
    host: 127.0.0.1
    port: 88
    state: started

- name: Wait for kadmind to become available
  wait_for:
    host: 127.0.0.1
    port: 749
    state: started

- name: kadmin initial user setup (1/3)
  template:
    src: kadmin.sh
    dest: /tmp/kadmin.sh
    owner: root
    group: root
    mode: 0700
  when: init and (inventory_hostname == groups['dc'][0])

- name: kadmin initial user setup (2/3)
  shell: /tmp/kadmin.sh
  when: init and (inventory_hostname == groups['dc'][0])

- name: kadmin initial user setup (3/3)
  file:
    path: /tmp/kadmin.sh
    state: absent

- name: Kerberize LDAP
  include: ldap_krb5.yml
