---
- hosts: audio
  become: true
  become_method: sudo
  roles:
    - network
    - xbps-repoconf
    - rsyslog
    - ntp
    - core-programs
    - sshd
    - cv-netkeys
    - audio
    - netlogon
    - nut-server
    - upsmon
    - telegraf
