---
- hosts: nas
  become: true
  become_method: sudo
  roles:
    - network
    - xbps-repoconf
    - rsyslog
    - ntp
    - core-programs
    - sshd
    - cv-netkeys
    - nas
    - netlogon
    - upsmon
    - telegraf
