---
# cups role will not be run, as we are currently managing it by hand until we switch to a containerized environment
- hosts: print
  become: true
  become_method: sudo
  roles:
    - network
    - xbps-repoconf
    - rsyslog
    - ntp
    - core-programs
    - sshd
    - cv-netkeys
    - papercut
    - netlogon
    - upsmon
    - telegraf
