---
- hosts: scroller
  become: true
  become_method: sudo
  roles:
    - network
    - xbps-repoconf
    - rsyslog
    - ntp
    - core-programs
    - sshd
    - cv-netkeys
    - scroller
    - netlogon
    - telegraf
