---
- hosts: ssh
  become: true
  become_method: sudo
  roles:
    - network
    - xbps-repoconf
    - rsyslog
    - ntp
    - core-programs
    - sshd
    - cv-netkeys
    - mosh
    - ssh-box
    - netlogon
    - upsmon
    - telegraf
