---
- hosts: dc:ssh:utility:audio:print:mediaboxen:workstation:scroller
  become: true
  become_method: sudo
  tasks:
    - xbps:
        update_cache: true
        upgrade: true
    - xbps:
        update_cache: true
        upgrade: true
