---
- name: Install theme dependencies
  xbps:
    pkg:
      - git-all
      - qt5-graphicaleffects
      - qt5-quickcontrols2

- name: Copy theme
  git:
    repo: git://github.com/collegiumv/sddm_wynn-theme.git
    dest: /usr/share/sddm/themes/sddm_wynn-theme
    depth: 1
  notify: sddm

- name: Download assets
  get_url:
    url: "{{ greeter_theme.wallpaper }}"
    dest: /usr/share/sddm/themes/sddm_wynn-theme/user_background.png
    owner: root
    group: root
    mode: 0644
  notify: sddm

- name: Copy logo
  copy:
    src: logo.png
    dest: /usr/share/sddm/themes/sddm_wynn-theme/logo.png
    owner: root
    group: root
    mode: 0644
  notify: sddm

- name: Install theme configuration file
  template:
    src: theme.conf
    dest: /usr/share/sddm/themes/sddm_wynn-theme/theme.conf.user
    owner: root
    group: root
    mode: 0644
  notify: sddm
