---
- name: Configure firewall
  copy:
    src: nslcd.rules
    dest: /etc/iptables.d/nslcd.rules
    owner: root
    group: root
    mode: 0640
  notify:
    - iptables

- name: Install libpam-ldapd
  xbps:
    pkg: nss-pam-ldapd
    state: present

- name: Configure libpam-ldapd
  copy:
    src: nslcd.conf
    dest: /etc/nslcd.conf
    owner: root
    group: nslcd
    mode: 0640
  notify:
    - nslcd

- name: Add ldap to nsswitch
  lineinfile:
    dest: /etc/nsswitch.conf
    regexp: '^{{ item }}:'
    line: '{{ item }}:         files ldap'
  with_items:
    - passwd
    - group
    - shadow

- name: Enable nslcd
  file:
    src: /etc/sv/nslcd
    dest: /var/service/nslcd
    state: link
