---
- name: Copy pasta files
  copy:
    src: pasta
    dest: /var/www/
    owner: root
    group: root
    mode: 0644
    directory_mode: 0755

- name: Add pasta site
  copy:
    src: pasta.conf
    dest: /etc/nginx/sites-available/pasta.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - nginx

- name: Enable pasta site
  file:
    src: ../sites-available/pasta.conf
    dest: /etc/nginx/sites-enabled/pasta.conf
    state: link
  notify:
    - nginx
