---
- name: Install packages
  xbps:
    pkg:
      - autox
      - feh
    state: present

- name: Create the kiosk group
  group:
    name: kiosk
    state: present

- name: Create a kiosk user
  user:
    name: kiosk
    groups: kiosk,video
    state: present

- name: Install xinitrc
  copy:
    src: xinitrc
    dest: /home/kiosk/.xinitrc
    owner: kiosk
    group: kiosk
    mode: 0750

- name: Ensure announcements path exists
  file:
    path: /opt/announcements
    state: directory
    owner: kiosk
    group: kiosk
    mode: 0755

- name: Ensure council mount path exists
  file:
    path: /opt/announcements
    state: directory

- name: Enable council nfs mount
  mount:
    path: /mnt/council_scroller
    src: nfs.collegiumv.org:/srv/council
    fstype: nfs
    opts: nolock,noatime,intr
    state: present

- name: Copy rsync script
  copy:
    src: update-scroller.sh
    dest: /home/kiosk/update-scroller.sh
    owner: kiosk
    group: kiosk
    mode: 0744

- name: Install scroller cron job
  copy:
    src: scroller.cron
    dest: /etc/cron.d/scroller.cron
    owner: root
    group: root
    mode: 0644

- name: Configure autox
  copy:
    src: conf
    dest: /etc/sv/autox/conf
    owner: root
    group: root
    mode: 0755

- name: Enable autox
  file:
    src: /etc/sv/autox
    dest: /var/service/autox
    state: link
