---
- name: Install netlogon packages
  xbps:
    pkg:
      - hxtools
      - libnfs
      - mit-krb5
      - nfs-utils
      - pam-krb5
      - pam-mount
    state: present

- name: Configure system-auth
  copy:
    src: system-auth
    dest: /etc/pam.d/system-auth
    owner: root
    group: root
    mode: 0644

- name: Configure pam_mount
  template:
    src: pam_mount.conf.xml
    dest: /etc/security/pam_mount.conf.xml
    owner: root
    group: root
    mode: 0644

- name: Copy firewall rules
  copy:
    src: netlogon.rules
    dest: /etc/iptables.d/netlogon.rules
    owner: root
    group: root
    mode: 0640
  notify:
    - iptables

- name: Grant Server Admins full sudo
  copy:
    src: cv.base
    dest: /etc/sudoers.d/cv_base
    owner: root
    group: root
    mode: 0644

- name: Create sudo lecture folder
  file:
    path: /usr/local/share/sudo/
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy sudo lecture
  copy:
    src: bee.lecture
    dest: /usr/local/share/sudo/bee.lecture
    owner: root
    group: root
    mode: 0644

- name: Copy sudo lecture config
  copy:
    src: lecture
    dest: /etc/sudoers.d/lecture
    owner: root
    group: root
    mode: 0644
